name: "Run PAUL"

on:
  # Workflow is triggered automatically when an issue is opened, reopened or edited.
  issues:
    types: [opened, reopened, edited]
  # Workflow can be triggered with a click of a button. User inputs issue number.
  workflow_dispatch:
    inputs:
      dispatch_issue_number:
        description: "Issue Number"
        required: true

# Need this for PAUL to make changes and open PRs
permissions:
  contents: write
  pull-requests: write

jobs:
  run-paul:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mikeraphk/paul:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show where repo is checked out
        run: |
          echo "GITHUB_WORKSPACE is $GITHUB_WORKSPACE"
          ls -al /__w/test_dir_1
          ls -al /__w/test_dir_1/test_dir_1

      - name: List /github/workspace immediately after checkout
        run: |
          echo "CWD: $(pwd)"
          ls -al /github/workspace || echo "/github/workspace does not exist"

      - name: Install tree and show directory structure
        run: |
          apt-get update && apt-get install -y tree
          tree -L 3 /
          echo
          tree -L 3 /github/workspace || echo "/github/workspace does not exist"

      - name: Run PAUL
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.PAUL_GITHUB_TOKEN }}
        run: |
          ISSUE_NUMBER="${{ github.event.issue.number }}"
          if [ -z "$ISSUE_NUMBER" ]; then
            ISSUE_NUMBER="${{ github.event.inputs.dispatch_issue_number }}"
          fi

          cd /app
          python3 /app/main.py github \
            --owner "${{ github.repository_owner }}" \
            --repo "${{ github.event.repository.name }}" \
            --issue "$ISSUE_NUMBER" \
            --model "gpt-4o-mini"
