name: "Run PAUL"

on:
  # Workflow can be triggered with a click of a button. User inputs issue number.
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue Number"
        required: true
  # Workflow is triggered automatically when an issue is opened/reopened
  issues:
    types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  run-paul:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PAUL Action
        uses: MikeRaphK/PAUL@rebuilding
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue: ${{ github.event.issue.number || github.event.inputs.issue_number }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.PAUL_GITHUB_TOKEN }}
