name: Run PAUL

on:
  issues:
    types: [opened, reopened]

jobs:
  run-paul:
    runs-on: ubuntu-latest
    steps:
      - name: Run PAUL
        uses: MikeRaphK/PAUL@develop
        with:
          repo_url: ${{ github.event.repository.html_url }}
          issue_number: ${{ github.event.issue.number }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.PAUL_GITHUB_TOKEN }}
