name: "Run PAUL"

on:
  # Workflow is triggered automatically when an issue is opened, reopened, labeled, or edited.
  issues:
    types: [opened, reopened, labeled, edited]
  # Workflow can be triggered with a click of a button. User inputs issue number.
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue Number"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  run-paul:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Show directory info BEFORE Docker action
      - name: Show working dir before Docker
        run: |
          echo "CWD: $(pwd)"
          ls -al
          echo "/app:"
          ls -al /app || echo "/app does not exist"
          echo "/github/workspace:"
          ls -al /github/workspace || echo "/github/workspace does not exist"

      # Run your Docker Action
      - name: Run PAUL Action
        id: paul
        uses: MikeRaphK/PAUL@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue: ${{ github.event.issue.number || inputs.issue_number }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.PAUL_GITHUB_TOKEN }}

      # Show directory info AFTER Docker action
      - name: Show working dir after Docker
        run: |
          echo "CWD: $(pwd)"
          ls -al
          echo "/app:"
          ls -al /app || echo "/app does not exist"
          echo "/github/workspace:"
          ls -al /github/workspace || echo "/github/workspace does not exist"
