name: "Run PAUL with GPT-4o"

on:
  # Workflow is triggered automatically when an issue is opened, reopened, labeled, or edited.
  issues:
    types: [opened, reopened, edited]
  # Workflow can be triggered with a click of a button. User inputs issue number.
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue Number"
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  run-paul:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run PAUL Action
        uses: MikeRaphK/PAUL@main
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          issue: ${{ github.event.issue.number || inputs.issue_number }}
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.PAUL_GITHUB_TOKEN }}
          model: "gpt-4o"
